### ISSUE TITLE
Mod conflict

### ISSUE THREAD

**Issue by kacperuro** [dsfhdshdjtsb/enchantments#2]
Conflict with Space Dimensions mod?

java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods agape_space and cenchants
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:85)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by dsfhdshdjtsb** [comment]
Sorry about that, apparently mixin file names need to be unique across different mods(I didn't know that). It should be fixed now on version 1.8.1.  Thanks for letting me know!
